services:
  postgres:
    image: docker.m.daocloud.io/postgres:16
    container_name: postgres_dla_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dla_db
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de desarrollo con hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dla_app_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/dla_db?schema=public
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

  # Servicio de producción
  prod:
    build: .
    container_name: dla_app_prod
    restart: unless-stopped
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/dla_db?schema=public
    networks: 
      - proxy
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  proxy:
    external: true
  app_network:
    driver: bridge

volumes:
  postgres_data:
